# Generated by Django 4.1.7 on 2023-03-09 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('meetup_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='speaker_images')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_email', models.EmailField(max_length=254, null=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('meetup_date', models.DateField(blank=True, null=True)),
                ('meetup_time', models.TimeField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('meetup_speakers', models.ManyToManyField(blank=True, null=True, to='meetupapp.speaker')),
                ('participant', models.ManyToManyField(blank=True, to='meetupapp.participant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
